-- AlterTable
ALTER TABLE `Usuario` ADD COLUMN `documento` VARCHAR(191) NULL,
    ADD COLUMN `email` VARCHAR(191) NULL,
    MODIFY `role` ENUM('SYSADMIN', 'PADRAO', 'QUIMICO') NOT NULL DEFAULT 'PADRAO';
